/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.TeacherController;
import javax.swing.JOptionPane;
import models.Teacher;

/**
 *
 * @author bhask
 */
public class FacultyPanel extends javax.swing.JFrame {

    /**
     * Creates new form FacultyPanel
     */
    Teacher teacher;
    public FacultyPanel(Teacher teacher) {
        this.teacher = teacher;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        AwardList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        editMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        LogoutMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        awardMenuItem = new javax.swing.JMenuItem();
        conferenceMenuItem = new javax.swing.JMenuItem();
        journalMenuItem = new javax.swing.JMenuItem();
        workshopMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AwardList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(AwardList);

        jTabbedPane1.addTab("Awards", jScrollPane1);
        jTabbedPane1.addTab("Conference", jScrollPane2);
        jTabbedPane1.addTab("Journal", jScrollPane3);
        jTabbedPane1.addTab("Workshop", jScrollPane4);

        jMenu2.setText("Welcome " + this.teacher.getFname());

        editMenuItem.setText("Edit Profile");
        editMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(editMenuItem);

        deleteMenuItem.setText("Delete Profile");
        deleteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(deleteMenuItem);

        LogoutMenuItem.setText("Logout");
        LogoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(LogoutMenuItem);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Create Achivement");

        awardMenuItem.setText("Award");
        awardMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                awardMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(awardMenuItem);

        conferenceMenuItem.setText("Conference");
        jMenu1.add(conferenceMenuItem);

        journalMenuItem.setText("Journal");
        jMenu1.add(journalMenuItem);

        workshopMenuItem.setText("Workshop");
        jMenu1.add(workshopMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMenuItemActionPerformed
        // TODO add your handling code here:
        updateFaculty upFaculty = new updateFaculty(teacher);
        upFaculty.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_editMenuItemActionPerformed

    private void LogoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutMenuItemActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_LogoutMenuItemActionPerformed

    private void deleteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuItemActionPerformed
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete your profile?", "Delete Profile",  JOptionPane.YES_NO_OPTION);
        if(input == 0){
            TeacherController teacherController = new TeacherController();
            int res = teacherController.deleteTeacher(this.teacher.getFid());
            if(res >= 1){
                JOptionPane.showMessageDialog(this, "teacher is successfully deleted");
                this.dispose();
                new Login().setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(this, "Problem occured when deleting teacher");
            }
        }
    }//GEN-LAST:event_deleteMenuItemActionPerformed

    private void awardMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_awardMenuItemActionPerformed
        // TODO add your handling code here:
        Award award = new Award(this.teacher);
        award.setVisible(true);
    }//GEN-LAST:event_awardMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacultyPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacultyPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacultyPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacultyPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacultyPanel(new Teacher()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> AwardList;
    private javax.swing.JMenuItem LogoutMenuItem;
    private javax.swing.JMenuItem awardMenuItem;
    private javax.swing.JMenuItem conferenceMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenuItem editMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem journalMenuItem;
    private javax.swing.JMenuItem workshopMenuItem;
    // End of variables declaration//GEN-END:variables
}
