/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AchivementAwardController;
import controller.AchivementConferenceController;
import controller.AchivementJournalController;
import controller.AchivementWorkshopController;
import java.util.ArrayList;
import models.AchievementAward;
import models.AchivementConference;
import models.AchivementJournal;
import models.AchivementWorkshop;
import models.Teacher;

/**
 *
 * @author bhask
 */
public class ShowAchivements extends javax.swing.JFrame {

    /**
     * Creates new form ShowAchivements
     */
    private Teacher teacher;
    public ShowAchivements(Teacher teacher) {
        this.teacher = teacher;
        initComponents();
    }
    
    private <T> String[] listToStrings(ArrayList<?> aList){
        String [] achivements = new String[aList.size()];
        for(int i=0; i< aList.size(); i++){
            achivements[i] = aList.get(i).toString();
        }
        return achivements;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText(teacher.getFullName() + " Achivement");
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            ArrayList<AchievementAward> awards = new AchivementAwardController().getAwards(teacher.getFid());
            String[] strings = listToStrings(awards);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jTabbedPane1.addTab("Awards", jScrollPane1);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            ArrayList<AchivementConference> confs = new AchivementConferenceController().getAwards(teacher.getFid());
            String[] strings = listToStrings(confs);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jTabbedPane1.addTab("Conferences", jScrollPane2);

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            ArrayList<AchivementJournal> journals = new AchivementJournalController().getAwards(teacher.getFid());
            String[] strings = listToStrings(journals);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList3);

        jTabbedPane1.addTab("Journal", jScrollPane3);

        jList4.setModel(new javax.swing.AbstractListModel<String>() {
            ArrayList<AchivementWorkshop> workshops = new AchivementWorkshopController().getAwards(teacher.getFid());
            String[] strings = listToStrings(workshops);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList4);

        jTabbedPane1.addTab("Workshop", jScrollPane4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
